version: 2.1
jobs:
 build:
  docker: 
   - katalonstudio/katalon
  steps:
   - checkout
   - run:
   		name: Execute Katalon Studio
   		command: katalon-execute.sh -browserType="Chrome" -retry=2 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"
   - store-test_results:
   		path: ./report
   - store-artifacts:
   		path: ./report